In [1]:
import numpy as np

list1 = [1,2,3,4,5]
a1 = np.array(list1)
print(a1[0])
print(a1[1])

1
2


In [12]:
list2 = [6,7,8,9,0]
a2 = np.array([list1,list2])
print(a2)
print(a2.shape)
print(a2[0,0])
print(a2[1,3])

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)
1
9


In [8]:
print(a1[ [1,3] ])  # we can also use a list as the index

[2 4]


In [10]:
print(a1 > 2)
print(a1[a1 > 2])  # Boolean indexing

[False False  True  True  True]
[3 4 5]


In [11]:
nums = np.arange(20)
odd_nums = nums[nums % 2 == 1]
print(odd_nums)

[ 1  3  5  7  9 11 13 15 17 19]


In [46]:
# slicing arrays

a = np.array([[1,2,3,4,5],
              [6,7,8,9,0],
              [9,8,7,6,5]])
b = a[1:3, 2:3] # row 1 to 3 (not inclusive) and column 0 to 3 (not inclusive)
print(b)
b = a[1:3, :3]  # row 1 to 3 (not inclusive) and column 0 to 3 (not inclusive)
print(b)
b = a[-2:, -3:]  # row -2 to 0 (not inclusive) and column -2 to 0 (not inclusive) 
print(b)

[[8]
 [7]]
[[6 7 8]
 [9 8 7]]
[[8 9 0]
 [7 6 5]]


In [48]:
# NumPy slice is a reference

reference = a[1:, 2:] # reference is pointing to a subset of a
print(reference)
reference[0,1] = 99
print(a)

[[8 9 0]
 [7 6 5]]
[[ 1  2  3  4  5]
 [ 6  7  8 99  0]
 [ 9  8  7  6  5]]


In [50]:
ref = a[2:, :] # ref is a rank 2 array
print(ref)
print(ref.shape)
ref = a[2, :] # here ref is a rank 1 array
print(ref)
print(ref.shape)

[[9 8 7 6 5]]
(1, 5)
[9 8 7 6 5]
(5,)


In [51]:
ref = ref.reshape(1,-1)
# The first 1 indicates that we want to convert it into rank 2 array with 1 row, 
# and the -1 indicates that we will leave it to the reshape() function 
# to create the correct number of columns

print(ref)
print(ref.shape)

[[9 8 7 6 5]]
(1, 5)


In [52]:
ref = ref.reshape(-1,)
# The -1 indicates that we let the function decide how many rows to create 
# as long as the end result is a rank 1 array.

print(ref)
print(ref.shape)

[9 8 7 6 5]
(5,)
