In [9]:
# copying by reference

import numpy as np

list = [[1,2,3,4], [5,6,7,8]]

A = np.array(list)
B = A # creates a copy of A by reference

print("A:\n", A)
print("\nB:\n", B)

# B is actually pointing to the original A. 
# So, any changes made to either array will affect the other

B[0][0] = 33
print("\nA:\n", A)
print("\nB:\n", B)

A.shape = 1,-1 # reshape A
print("\nA:\n", A)
print("\nB:\n", B)

A:
 [[1 2 3 4]
 [5 6 7 8]]

B:
 [[1 2 3 4]
 [5 6 7 8]]

A:
 [[33  2  3  4]
 [ 5  6  7  8]]

B:
 [[33  2  3  4]
 [ 5  6  7  8]]

A:
 [[33  2  3  4  5  6  7  8]]

B:
 [[33  2  3  4  5  6  7  8]]


In [13]:
# Copying by View (Shallow Copy)

A = np.array(list)
B = A.view() # creates a copy of A by reference, but changes in dimension in A will not affect B

print("A:\n", A)
print("\nB:\n", B)

# As usual, modify a value in A and we will see the changes in B:
A[0][0] = 33
print("\nA:\n", A)
print("\nB:\n", B)

# But with shallow copying, when we change the shape of A,
# B is unaffected:
A.shape = 1,-1 # reshape A
print("\nA:\n", A)
print("\nB:\n", B)

A:
 [[1 2 3 4]
 [5 6 7 8]]

B:
 [[1 2 3 4]
 [5 6 7 8]]

A:
 [[33  2  3  4]
 [ 5  6  7  8]]

B:
 [[33  2  3  4]
 [ 5  6  7  8]]

A:
 [[33  2  3  4  5  6  7  8]]

B:
 [[33  2  3  4]
 [ 5  6  7  8]]


In [14]:
# Copying by Value (Deep Copy)

A = np.array(list)
B = A.copy() # creates a copy of A by value (deep copy)

print("A:\n", A)
print("\nB:\n", B)

# any changes made to the shape of the original array will not affect its copy:
A[0][0] = 33
print("\nA:\n", A)
print("\nB:\n", B)

A.shape = 1,-1 # reshape A
print("\nA:\n", A)
print("\nB:\n", B)

A:
 [[1 2 3 4]
 [5 6 7 8]]

B:
 [[1 2 3 4]
 [5 6 7 8]]

A:
 [[33  2  3  4]
 [ 5  6  7  8]]

B:
 [[1 2 3 4]
 [5 6 7 8]]

A:
 [[33  2  3  4  5  6  7  8]]

B:
 [[1 2 3 4]
 [5 6 7 8]]
