In [7]:
import numpy as np

x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

print("x:\n", x)
print("y:\n", y)
print("\nsum:\n", x + y)
print("\nrest:\n", x - y)
print("\nproduct:\n", x * y)
print("\ndivision:\n", x / y)

x:
 [[1 2]
 [3 4]]
y:
 [[5 6]
 [7 8]]

sum:
 [[ 6  8]
 [10 12]]

rest:
 [[-4 -4]
 [-4 -4]]

product:
 [[ 5 12]
 [21 32]]

division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [8]:
names = np.array(['Ann','Joe','Mark'])
heights = np.array([1.5, 1.78, 1.6])
weights = np.array([65, 46, 59])

bmi = weights / heights**2
print(bmi)

print("Overweight: ", names[bmi>25])
print("Underweight: ", names[bmi<18.5])
print("Healthy: ", names[(bmi>=18.5) & (bmi<=25)])

[28.88888889 14.51836889 23.046875  ]
Overweight:  ['Ann']
Underweight:  ['Joe']
Healthy:  ['Mark']


In [9]:
x = np.array([2,3])
y = np.array([4,2])

print("(x,y) = ", np.dot(x,y))

(x,y) =  14


In [16]:
# matrix multiplication

A = np.array([[1,2,3],[2,3,4]])
B = np.array([[1,2],[2,1], [2,-1]])

print("A:\n", A)
print("\nB:\n", B)
print("\nAB:\n", np.dot(A,B))

A:
 [[1 2 3]
 [2 3 4]]

B:
 [[ 1  2]
 [ 2  1]
 [ 2 -1]]

AB:
 [[11  1]
 [16  3]]


In [22]:
# cumulative sumb

A = np.array([(1,2,3),(4,5,6), (7,8,9)])
print("A:\n", A)

print("\nA.cumsum:\n", A.cumsum())
print("\nA.cumsum(axis = 0):\n", A.cumsum(axis = 0)) # sum over rows for each of the 3 columns
print("\nA.cumsum(axis = 1):\n", A.cumsum(axis = 1)) # sum over columns for each of the 3 rows

A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

A.cumsum:
 [ 1  3  6 10 15 21 28 36 45]

A.cumsum(axis = 0):
 [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]

A.cumsum(axis = 1):
 [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [25]:
# NumPy sorting

ages = np.array([34,12,37,5,13])

sorted_ages = np.sort(ages) # does not modify the original array
print("sorted ages:\n", sorted_ages)
print("\nages:\n", ages)

ages.sort() # modifies the array
print("\nages:\n", ages) 

sorted ages:
 [ 5 12 13 34 37]

ages:
 [34 12 37  5 13]

ages:
 [ 5 12 13 34 37]


In [35]:
# argsort()

ages = np.array([34,12,37,5,13])
indices = ages.argsort()

print("indices:\n", indices)
print("\nages[indices]:\n", ages[indices])

# application

persons = np.array(['Johnny','Mary','Peter','Will','Joe'])
ages    = np.array([34,12,37,5,13])
heights = np.array([1.76,1.2,1.68,0.5,1.25])

print("\nsort by age:\n")
sort_indices = np.argsort(ages)
print(persons[sort_indices])
print(ages[sort_indices])
print(heights[sort_indices])

print("\nsort by name:\n")
sort_indices = np.argsort(persons)
print(persons[sort_indices])
print(ages[sort_indices])
print(heights[sort_indices])

print("\nreversed sort by name:\n")
reverse_sort_indices = np.argsort(persons)[::-1] # reverse the order of a list
print(persons[reverse_sort_indices])
print(ages[reverse_sort_indices])
print(heights[reverse_sort_indices])

indices:
 [3 1 4 0 2]

ages[indices]:
 [ 5 12 13 34 37]

sort by age:

['Will' 'Mary' 'Joe' 'Johnny' 'Peter']
[ 5 12 13 34 37]
[0.5  1.2  1.25 1.76 1.68]

sort by name:

['Joe' 'Johnny' 'Mary' 'Peter' 'Will']
[13 34 12 37  5]
[1.25 1.76 1.2  1.68 0.5 ]

reversed sort by name:

['Will' 'Peter' 'Mary' 'Johnny' 'Joe']
[ 5 37 12 34 13]
[0.5  1.68 1.2  1.76 1.25]
