In [14]:
list1 = [2,3,5,7]
print(list1)

[2, 3, 5, 7]


In [15]:
list2 = [2,"Hello",3.14,True,5]
print(list2)

[2, 'Hello', 3.14, True, 5]


In [2]:
import numpy as np
a1 = np.arange(10)
print(a1)
print(a1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [3]:
a2 = np.arange(0,10,2)
print(a2)

[0 2 4 6 8]


In [4]:
a3 = np.zeros(5)
print(a3)
print(a3.shape)

[0. 0. 0. 0. 0.]
(5,)


In [8]:
a4 = np.zeros((2,3))
print(a4)
print(a4.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [10]:
a5 = np.full((2,3), 5)
print(a5)

[[5 5 5]
 [5 5 5]]


In [12]:
a6 = np.eye(4)
print(a6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
a7 = np.random.random((2,4))
print(a7)

[[0.12561222 0.35093755 0.14667709 0.60819453]
 [0.51089201 0.959144   0.38018069 0.80674442]]


In [18]:
a8 = np.array(list1)
print(a8)

[2 3 5 7]
